config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'pages#home'
  get "users", to: "users#show"
  get 'thanks', to: 'pages#thanks'
  get 'breakdown', to: 'pages#breakdown'
  get 'faq', to: 'pages#faq'
  get 'events', to: 'events#index'
  get 'profile', to: 'pages#profile'
  
  resources :children
  resources :user do
    member do
      get :confirm_email
    end
  end
  resources :participations
  resources :events
  resources :contact, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord

    belongs_to :user, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :participations
    has_many :users, through: :participations
    # accepts_nested_attributes_for :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
      
  has_many :children, dependent: :destroy
  accepts_nested_attributes_for :children, allow_destroy: true, reject_if: :all_blank
  has_many :participations
  has_many :events, through: :participations

  # validates :email, :presence => true, :email => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        if current_user.admin?
            users_path
        else
            root_path
        end
    end

    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

    def new
        @child = Child.new
    end

    def create
        @child = Child.new(child_params)
        @child.user_id = current_user.id
        @child.save
        redirect_to profile_path
    end

    private

    def child_params
        params.require(:child).permit(:first_name, :age, :user_id)
    end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

    private
        def after_confirmation_path_for(resource_name, resource)
            sign_in(resource)
            new_child_path
        end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @events = Event.all
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:home, :breakdown, :faq]

    def home
    end

    def thanks
    end

    def breakdown
    end

    def faq
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        if current_user.admin?
            @users = User.all
        else
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lilypad Tales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="/home.js" alt="home.js"></script>
    <link rel="application" type="text/css" href="application.css">
    <!-- <link rel="application" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" /> -->
    <script src="https://kit.fontawesome.com/34f56d6676.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
      /* a { color: #ff9500; } CSS link color */
    </style>
  </head>

  <body>
    <div class="container-fluid">
    <div class="background">
    <ul id="navigation">
      <li class="nav-item"><%= link_to "Home", root_path%></li>
      <li class="nav-item"><%= link_to 'Program', root_path(anchor: 'heading') %></li>
      <li class="nav-item"><%= link_to 'Educator', root_path(anchor: 'educator-heading') %></li>
      <li class="nav-item"><%= link_to 'Contact', root_path(anchor: 'icon') %></li>
      <li class="nav-item"><%= link_to "FAQs", faq_path%></li>
      <li class="nav-signup">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.first_name.capitalize %></strong>
        <%= link_to 'Profile', profile_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </li>
    </ul>

    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/pages/breakdown.html.erb
<div class="breakdown">
            <h3 id="program-heading">Program breakdown</h3>
            <div class="text-section">
                <div class="job-description">
                    <p class="paragraph">
                        TOPIC 1<br>
                        LORD GANESHA<br>
                        ___________________________________________________<br>
                    </p>
                    <p class="paragraph">
                        TOPIC 2<br>
                        WHAT’S THE WEATHER OUTSIDE?<br>
                        ___________________________________________________<br>
                    </p>
                    <p class="paragraph">
                        TOPIC 3<br>
                        COUNTING WITH INDIAN SWEET TREAT<br>
                        ___________________________________________________<br>
                    </p>
                    <p class="paragraph">
                        TOPIC 4<br>
                        WHERE DO WE LIVE?
                    </p>
                </div>
            </div>
        </div>

app/views/pages/faq.html.erb
<div class="breakdown">
            <h3 id="heading">FAQs</h3>
            <div class="text-section">
                <div class="job-description">
                    <p class="faq-paragraph">
                        <p class="question">What is the fee?</p>
                        <p class="paragraph-left">This program is free of cost.</p><br><br>
                        <p class="question">Do we (parents/children) have to participate every week?</p>
                        <p class="paragraph-left">Yes</p><br><br>
                        <p class="question">Do parents have to participate during the sessions?</p>
                        <p class="paragraph-left">Parents do not have to participate during the sessions, however it
                        is a great opportunity for bonding with your child as well as
                        watching your little ones learn and encouraging them.</p><br><br>
                    </p>
                </div>
            </div>
        </div>

app/views/pages/home.html.erb
<body>
    <!--CSS GRID MAIN-->
    <div class="container">

        <div class="center-align">
            <h1 class="header">Welcome</h1>
            <span class="title-sub-header">“GEAR UP FOR KINDERGARTEN!”</span>
        </div>
        <div class="intro">
            <div class="gallery-images">
                <div class="projects">
                    <%= image_tag('fam.jpg', :class => "placeholder") %>
                    <p class="paragraph-left">
                    With so many hindrances and unanswered questions we are facing daily, questions and fear
                    regarding our children’s learning progress shouldn’t be one of them. That is why I have taken
                    the initiative in delivering age appropriate education, in the most fun ways, to your little
                    ones at the comfort of your own home.<br><br> I cannot promise what our economy has for us 4 weeks
                    from now but I can say with confidence that your children will be exploring, engaging and
                    getting a head start at learning on this fun journey.
                    </p>
                </div>
            </div>
        </div>
        <div class="cv">
            <h3 id="heading">About the program</h3>
            <div class="text-section">
                <div class="job-description">
                    <p class="paragraph-left">
                        You may be wondering, how exactly does this program work? Or how should you, as parents,
                        be prepared for this program every week for 4 weeks? Here are all your queries answered: as
                        parents, all you have to do is sign up to this program, for free, and join us online once a week for 30
                        mins. That is all! This program will include a story, an activity task, craft ideas, all centered around
                        the topic of the week. Most conveniently, the resources allocated every week will be provided with this package! In other words,
                        you do not have to go out and buy any materials or books to sign up for this program. All the
                        required resources will be provided for free!<br><br> 
                        <p class="question">WHO IS THIS PROGRAM FOR:</p> <p class="paragraph-left">This program is for children aged 3-5 years.</p><br>
                        <p class="question">WHAT WILL THE CHILDREN LEARN:</p> <p class="paragraph-left">Children will be exposed to topics
                        that they should be familiar with before they start kindergarten.
                        As well as a designated activity or craft for each week, this
                        program will also provide extension tasks for those of you who
                        choose to do them at their own pace.</p><br>
                        <p class="question">WHEN/WHERE:</p> <p class="paragraph-left">At the comfort of your own house, I will be visiting
                        your family via Skype once a week. Currently, this pilot program is only available to a selection of families
                        residing inside of Folsom.</p> 
                    </p>
                </div>
            </div>
        </div>
        <h3 id="educator-heading">About the educator</h3>
        <div class="intro">
            <div class="gallery-images">
                <div class="educator">
                    <p class="paragraph-left">
                    My name is Vidhya and I am very excited to visit you and your little ones at home for the next 4
                    weeks!<br><br>
                    I am a fully qualified kindergarten teacher, currently working as an assistant director at a
                    preschool. I have taught in classrooms for over 6 years, specializing in teaching ESL students.
                    (English as Second Language). I am and always have been passionate about igniting young minds, 
                    stimulating their abilities and kindling a genuine love for learning.
                    </p>
                    <%= image_tag('vidhya.jpg', :class => "vidhya-pic") %>
                </div>
            </div>
        </div>
        <div class="contact">
            <p id="heading">CONTACT</p>
        </div>

        <div class="icon-position">
            <a href="https://www.instagram.com/theammainme/?hl=en"><i id="icon" class="fab fa-instagram"></i></a>
            <a><i id="icon" class="fas fa-envelope"></i></a>
        </div>

    </div>
</body>

</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="/index.js" alt="index.js"></script>
    <link rel="stylesheet" type="text/css" href="stylesheet.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <script src="https://kit.fontawesome.com/34f56d6676.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
</head>

<body>
    <!--CSS GRID MAIN-->
    <div class="container">
        <ul id="navigation">
            <li class="nav-logo"><img style="width:60px; height:60px; margin-right:130px;" src="images/family.png"></li>
            <li class="nav-item">Program</li>
            <li class="nav-item">Educator</li>
            <li class="nav-item">Contact</li>
            <li class="nav-item">FAQs</li>
        </ul>

        <div class="center-align">
            <h1 class="header">Welcome</h1>
            <span class="title-sub-header">“LETS GET READY FOR KINDERGARTEN” - PART 1</span>
        </div>
        <div class="intro">
            <div class="gallery-images">
                <div class="projects">
                    <img class="placeholder" src="images/placeholder.png">
                    <p class="paragraph-left">
                        With so many hindrances and unanswered questions we are facing daily,
                        questions and fear regarding our children’s learning progress shouldn’t be
                        one of them. That is why I have taken the initiative in delivering age
                        appropriate education, in the most fun-nest ways, to your little ones at the
                        comfort of your own home.<br><br> I cannot promise what our economy has for us 5
                        weeks from now but I can say with confidence that your children will be
                        exploring, engaging and getting a head start at learning when our nation is
                        ready to end lock down.
                </div>
            </div>
        </div>
        <div class="cv">
            <h3 id="heading">About the program</h3>
            <div class="text-section">
                <div class="job-description">
                    <p class="paragraph">
                        You may be wondering, how exactly does this program work? Or how should
                        you, as parents, be prepared for this program every week for 5 weeks? Here are all your queries
                        answered: as parents, all you have to do is sign up to
                        this program, for free, and log on once a week for 30 mins. That is all! This
                        program will include a story time, an activity task, craft ideas and most
                        conveniently, the resources allocated every week is provided with this package! In other words,
                        you do not have to go out and buy any materials
                        or books to sign-up for this program. All the required resources will be
                        provided for free!<br><br> WHO IS THIS PROGRAM FOR: This program is for children aged 3-5
                        years.<br><br>
                        WHAT WILL THE CHILDREN LEARN: Children will be exposed to topics
                        that they should be familiar with before they start kindergarten.
                        As well as a designated activity or craft for each week, this
                        program will also provide extension tasks for those of you who
                        chooses to do them at their own pace.
                        WHEN/WHERE: At the comfort of your own house, I will be visiting
                        your family via google meet once a week. Currently it is only
                        available for any families residing inside the USA.
                    </p>
                </div>
            </div>
        </div>
        <div class="contact">
            <p class="heading">CONTACT</p>
        </div>

        <div class="icon-position">
            <a><i id="icon" class="fab fa-instagram"></i></a>
            <a><i id="icon" class="fas fa-envelope"></i></a>
        </div>

    </div>
</body>

</html>

app/views/pages/profile.html.erb
<main class="container">
    <div class="user-info">
        <h1 class="header">Profile</h1>
    </div>
    <div>
        <h2>Name:</h2>
        <h3><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %></h3><br>
        <h2>Email:</h2>
        <h3><%= current_user.email %><h3><br>
        <h2>Enrolled Children:</h2>
        <% current_user.children.each do |child| %>
        <h3><%= child.first_name.capitalize %></h3>
        <% end %>
        <% if current_user.children.exists? %>
            <%= link_to 'Add another child', new_child_path %>
        <% else %>
            <%= link_to 'Add child', new_child_path %>
        <% end %>
    </div><br>
    <%= link_to 'Edit profile', edit_user_registration_path %>
</main>

app/views/pages/thanks.html.erb
<h1>Thank you for signing up! 🚀</h1><br />
<h2>Please expect an email from us shortly!</h2>